name: Development

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  # Validations
  validations:
    name: Validations
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Install Dependencies
      - name: Install Dependencies
        run: bun install

      # Run Lint
      - name: Run Lint
        run: bun install

      # Run Type Check
      - name: Run Type Check
        run: bun run tsc

      # Run Unit Tests
      - name: Run Unit Tests
        run: bun run test

  # Build
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: validations
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Install Dependencies
      - name: Install Dependencies
        run: bun install

      # Run Build
      - name: Run Build
        run: bun build:dev

      # Upload Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  # Deploy
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Download Artifact
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
